export const NORM_EDIT_REQUEST ='NORM_EDIT_REQUEST'
export const NORM_EDIT_SUCCESS ='NORM_EDIT_SUCCESS'
export const NORM_EDIT_FAIL ='NORM_EDIT_FAIL';

export const NORM_REQUEST ='NORM_REQUEST'
export const NORM_SUCCESS ='NORM_SUCCESS'
export const NORM_FAIL ='NORM_FAIL';

export const QUARTER_EDIT_REQUEST ='QUARTER_EDIT_REQUEST'
export const QUARTER_EDIT_SUCCESS ='QUARTER_EDIT_SUCCESS'
export const QUARTER_EDIT_FAIL ='QUARTER_EDIT_FAIL';

export const QUARTER_REQUEST ='QUARTER_REQUEST'
export const QUARTER_SUCCESS ='QUARTER_SUCCESS'
export const QUARTER_FAIL ='QUARTER_FAIL';

export const SUBMISSION_REQUEST ='SUBMISSION_REQUEST'
export const SUBMISSION_SUCCESS ='SUBMISSION_SUCCESS'
export const SUBMISSION_FAIL ='SUBMISSION_FAIL';

export const FORM_DATA_REQUEST ='FORM_DATA_REQUEST'
export const FORM_DATA_SUCCESS ='FORM_DATA_SUCCESS'
export const FORM_DATA_FAIL ='FORM_DATA_FAIL';


export const TIME_EDIT_REQUEST ='TIME_EDIT_REQUEST'
export const TIME_EDIT_SUCCESS ='TIME_EDIT_SUCCESS'
export const TIME_EDIT_FAIL ='TIME_EDIT_FAIL';


export const GET_COUNT_REQUEST ='GET_COUNT_REQUEST'
export const GET_COUNT_SUCCESS ='GET_COUNT_SUCCESS'
export const GET_COUNT_FAIL ='GET_COUNT_FAIL';

export const CLEAR_ERRORS ='CLEAR_ERRORS';

